# Generated by Django 2.0.3 on 2018-04-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='gag',
            new_name='tag',
        ),
    ]
