# Generated by Django 2.0.3 on 2018-04-26 02:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='group_tags', to='info.Tag'),
        ),
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='squads', to=settings.AUTH_USER_MODEL),
        ),
    ]
