# Generated by Django 2.0.3 on 2018-04-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20180407_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(default='', upload_to='images/group'),
            preserve_default=False,
        ),
    ]
