# Generated by Django 2.0.3 on 2018-04-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_group_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(default='', upload_to='images/album'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(default='', upload_to='images/artist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.ImageField(default='', upload_to='images/tag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='image',
            field=models.ImageField(default='', upload_to='images/track'),
            preserve_default=False,
        ),
    ]
